### ISSUE TITLE
Please add g4mespeed

### ISSUE THREAD

**Issue by Sussy-OS** [paperclip-universe/Redstonality#1]
Could you please add g4mespeed, and g4mespeed capture & playback?

**Comment by Wyatt-Stanke** [comment]
oh wow didn't expect people to actually use my modpack ok i'll try

**Comment by Sussy-OS** [comment]
> oh wow didn't expect people to actually use my modpack ok i'll try

Alright, thanks! This is a really good modpack btw!

**Comment by Wyatt-Stanke** [comment]
Added in 0.1.2-beta.6--sorry for the delay!

**Comment by Sussy-OS** [comment]
> Added in 0.1.2-beta.6--sorry for the delay!

Thanks! No problem at all.
